language: go
sudo: false

notifications:
  email:
    recipients:
      - focinfi@gmail.com
  on_success: change
  on_failure: always

go: stable

script:
  - go test ./address ./crypto/... ./key ./serializers ./utils -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)