package ckbtypes

type BlockHeader struct {
	CompactTarget    string `json:"compact_target"`
	Hash             string `json:"hash"`
	Number           string `json:"number"`
	ParentHash       string `json:"parent_hash"`
	Nonce            string `json:"nonce"`
	Timestamp        string `json:"timestamp"`
	TransactionsRoot string `json:"transactions_root"`
	ProposalsHash    string `json:"proposals_hash"`
	UnclesHash       string `json:"uncles_hash"`
	Version          string `json:"version"`
	Epoch            string `json:"epoch"`
	DAO              string `json:"dao"`
}

type AutoGenerated struct {
	BytesLimit string `json:"bytes_limit"`
	Cellbase   struct {
		Cycles interface{} `json:"cycles"`
		Data   struct {
			CellDeps   []interface{} `json:"cell_deps"`
			HeaderDeps []interface{} `json:"header_deps"`
			Inputs     []struct {
				PreviousOutput struct {
					Index  string `json:"index"`
					TxHash string `json:"tx_hash"`
				} `json:"previous_output"`
				Since string `json:"since"`
			} `json:"inputs"`
			Outputs []struct {
				Capacity string `json:"capacity"`
				Lock     struct {
					Args     []string `json:"args"`
					CodeHash string   `json:"code_hash"`
					HashType string   `json:"hash_type"`
				} `json:"lock"`
				Type interface{} `json:"type"`
			} `json:"outputs"`
			OutputsData []string `json:"outputs_data"`
			Version     string   `json:"version"`
			Witnesses   []struct {
				Data []string `json:"data"`
			} `json:"witnesses"`
		} `json:"data"`
		Hash string `json:"hash"`
	} `json:"cellbase"`
	CompactTarget    string        `json:"compact_target"`
	CurrentTime      string        `json:"current_time"`
	CyclesLimit      string        `json:"cycles_limit"`
	Dao              string        `json:"dao"`
	Epoch            string        `json:"epoch"`
	Number           string        `json:"number"`
	ParentHash       string        `json:"parent_hash"`
	Proposals        []interface{} `json:"proposals"`
	Transactions     []interface{} `json:"transactions"`
	Uncles           []interface{} `json:"uncles"`
	UnclesCountLimit string        `json:"uncles_count_limit"`
	Version          string        `json:"version"`
	WorkID           string        `json:"work_id"`
}
